services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
    depends_on:
      - web

  web:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wtunBwVrgdFMsmWf
      MYSQL_DATABASE: gdeuqhlz_project
      MYSQL_USER: user_db
      MYSQL_PASSWORD: wtunBwVrgdFMsmWf
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wtunBwVrgdFMsmWf
    depends_on:
      - db
    ports:
      - "8081:80"

volumes:
  db_data:
