@startuml class diagram

class Users {
    + user_id
    + email 
    + password
    + nama_depan
    + nama_belakang
    + no_hp
    + role
}

Users "1" -- "1" Auth
Database "1" *-- "1" Auth

class Database {
    - host
    - username
    - password
    - database

    + getConnect()
}
note top of Database: Buka koneksi ke database

class Auth {
    + error

    + loginUser()
    + registUser()
}

Users "1" -- "1" Profile

class Profile {
    + showProfileUser()
    + historyOrder()
    + orderActive()
    + cancelOrder()
}

class Tiket {
    + listTiket()
    + buyTiket()
    + searchTiket()
}

class HandleTopup {
    + listRequestTopup()
    + detailTopup()
}

@enduml
